# Generated by Django 5.2.5 on 2025-08-25 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Other Expense',
                'verbose_name_plural': 'Other Expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-bill_date'], 'verbose_name': 'Sales Bill', 'verbose_name_plural': 'Sales Bills'},
        ),
        migrations.AlterModelOptions(
            name='billitem',
            options={'verbose_name': 'Bill Item', 'verbose_name_plural': 'Bill Items'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='finishedproduct',
            options={'verbose_name': 'Finished Product', 'verbose_name_plural': 'Finished Products'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['-production_date'], 'verbose_name': 'Production Entry', 'verbose_name_plural': 'Production Entries'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'verbose_name': 'Raw Material', 'verbose_name_plural': 'Raw Materials'},
        ),
        migrations.AlterModelOptions(
            name='wheatpurchase',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Wheat Purchase', 'verbose_name_plural': 'Wheat Purchases'},
        ),
        migrations.AddField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='has_stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wheatpurchase',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Bill Date'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management.bill', verbose_name='Sales Bill'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Per Unit'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.finishedproduct', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity (Kg)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='current_stock_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Current Stock (Kg)'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='production',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.finishedproduct', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='production',
            name='production_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Production Date'),
        ),
        migrations.AlterField(
            model_name='production',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity Produced (Kg)'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='current_stock_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Current Stock (Kg)'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Raw Material Name'),
        ),
        migrations.AlterField(
            model_name='wheatpurchase',
            name='other_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Other Expenses'),
        ),
        migrations.AlterField(
            model_name='wheatpurchase',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], max_length=6, verbose_name='Payment Mode'),
        ),
        migrations.AlterField(
            model_name='wheatpurchase',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Per Kg'),
        ),
        migrations.AlterField(
            model_name='wheatpurchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='wheatpurchase',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity (Kg)'),
        ),
    ]
