# Generated by Django 5.2.5 on 2025-08-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_expense_alter_bill_options_alter_billitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='cost_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost Per Kg'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='mrp_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='MRP Per Kg'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='raw_material_ratio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Raw Material Used (Per Kg)'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='selling_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Selling Price Per Kg'),
        ),
    ]
