# Generated by Django 5.2.5 on 2025-08-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_finishedproduct_cost_per_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='bill',
            name='has_gst',
            field=models.BooleanField(default=True, verbose_name='Include GST'),
        ),
        migrations.AddField(
            model_name='bill',
            name='other_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Other Expenses'),
        ),
    ]
