# Generated by Django 5.2.5 on 2025-08-25 22:03

import django.db.models.deletion
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_bill_total_amount_bill_has_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='product',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='production',
            name='finished_product',
            field=models.ForeignKey(default=management.models.get_first_finished_product_pk, on_delete=django.db.models.deletion.CASCADE, to='management.finishedproduct'),
        ),
        migrations.AddField(
            model_name='production',
            name='raw_material',
            field=models.ForeignKey(default=management.models.get_first_raw_material_pk, on_delete=django.db.models.deletion.CASCADE, to='management.rawmaterial'),
        ),
        migrations.AddField(
            model_name='wheatpurchase',
            name='raw_material',
            field=models.ForeignKey(default=management.models.get_first_raw_material_pk, on_delete=django.db.models.deletion.CASCADE, to='management.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='product',
            field=models.ForeignKey(default=management.models.get_first_finished_product_pk, on_delete=django.db.models.deletion.CASCADE, to='management.finishedproduct'),
        ),
    ]
