# Generated by Django 5.2.5 on 2025-08-26 00:03

import django.db.models.deletion
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_production_product_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='product',
            field=models.ForeignKey(default=management.models.get_first_finished_product_pk, on_delete=django.db.models.deletion.CASCADE, to='management.finishedproduct', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='production',
            name='finished_product',
            field=models.ForeignKey(default=management.models.get_first_finished_product_pk, on_delete=django.db.models.deletion.CASCADE, to='management.finishedproduct', verbose_name='Finished Product'),
        ),
        migrations.AlterField(
            model_name='production',
            name='raw_material',
            field=models.ForeignKey(default=management.models.get_first_raw_material_pk, on_delete=django.db.models.deletion.CASCADE, to='management.rawmaterial', verbose_name='Raw Material'),
        ),
        migrations.AlterField(
            model_name='wheatpurchase',
            name='raw_material',
            field=models.ForeignKey(default=management.models.get_first_raw_material_pk, on_delete=django.db.models.deletion.CASCADE, to='management.rawmaterial', verbose_name='Raw Material'),
        ),
    ]
